### ISSUE TITLE
Does not start at all

### ISSUE THREAD

**Issue by jze1** [Kong/mockbin#99]
The documentation here is missing something or the sources are broken:
```
# npm start

> mockbin@1.6.2 start /root
> node bin/mockbin

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/bin/mockbin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mockbin@1.6.2 start: `node bin/mockbin`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mockbin@1.6.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-27T08_55_30_664Z-debug.log
```

**Comment by jze1** [comment]
So, when ```npm install mockbin``` is not the way to install it, I tried to build a docker image:
```npm WARN package.json mockbin@1.6.2 No README data
npm WARN package.json mockbin@1.6.2 No bin file found at bin/mockbin
npm WARN deprecated debug-log@2.0.0: This package is no longer relevant as Node.js 0.12 is unmaintained.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated codeclimate-test-reporter@0.5.1: codeclimate-test-reporter has been deprecated in favor of our new unified test-reporter. Please visit https://docs.codeclimate.com/docs/configuring-test-coverage for details on setting up the new test-reporter.
npm WARN deprecated echint@4.0.2: no longer maintained
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm ERR! Linux 5.4.0-1038-aws
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: cz-conventional-changelog@'>=3.1.0 <4.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0","1.0.1","1.1.0","1.1.1","1.1.2","1.1.3","1.1.4","1.1.5","1.1.6","1.1.7","1.2.0","2.0.0","2.1.0"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'mockbin'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1
```

**Comment by Vye** [comment]
I was hoping I could use this app but it doesn't build. :(

```
 docker build -t mockbin .
[+] Building 36.1s (7/9)
 => [internal] load build definition from Dockerfile                                                                                                                                                                                          0.1s
 => => transferring dockerfile: 137B                                                                                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/node:0.10-onbuild                                                                                                                                                                          2.2s
 => [internal] load build context                                                                                                                                                                                                             0.1s
 => => transferring context: 1.26MB                                                                                                                                                                                                           0.1s
 => [1/2] FROM docker.io/library/node:0.10-onbuild@sha256:ad41527a477b1a0efeb0f4fc52b799f7ccd9567c8c20230630844530ecff94aa                                                                                                                   30.3s
 => => resolve docker.io/library/node:0.10-onbuild@sha256:ad41527a477b1a0efeb0f4fc52b799f7ccd9567c8c20230630844530ecff94aa                                                                                                                    0.0s
 => => sha256:386a066cd84a33a04d560c42bef66d1dd64ebfc76de78550e5fd0f8d57778bca 51.36MB / 51.36MB                                                                                                                                              7.9s
 => => sha256:75ea8418708338e40dce9179cfe97fd116831f1601be50fef48ea6011653c986 18.53MB / 18.53MB                                                                                                                                              3.5s
 => => sha256:ad41527a477b1a0efeb0f4fc52b799f7ccd9567c8c20230630844530ecff94aa 2.00kB / 2.00kB                                                                                                                                                0.0s
 => => sha256:75089ac1f7aa828dab88b40cad241abac7786b03fee6813c16b94ec33613425d 6.14kB / 6.14kB                                                                                                                                                0.0s
 => => sha256:88b459c9f665cc39ff5fc09071b5dada4dad766573d962276f999d0c466d5405 42.50MB / 42.50MB                                                                                                                                              7.6s
 => => sha256:1e3ee139a57774dc3728a4bf9675bc379458093585e42f384852e644b1b272ac 129.81MB / 129.81MB                                                                                                                                           16.7s
 => => sha256:bd2400e7d880dc68db3c01d136b8ee8ed6e846bbc2c97ac0655597a0b11b573a 2.06kB / 2.06kB                                                                                                                                                8.9s
 => => sha256:b8c6812ba46984862fae512c3d1de8299a6819c8159fe022808ec254dc995cc6 97.21kB / 97.21kB                                                                                                                                              8.8s
 => => sha256:b24acc262d38a6dd1959ea2863d9c951d977cee55ba0a2f2cb06259a1e1397d1 126B / 126B                                                                                                                                                    9.1s
 => => sha256:0adf07c73141acdb79f289dae7b3a5d8cd2c97c734489092363af2bb7029616a 7.00MB / 7.00MB                                                                                                                                               10.1s
 => => extracting sha256:386a066cd84a33a04d560c42bef66d1dd64ebfc76de78550e5fd0f8d57778bca                                                                                                                                                     6.4s
 => => extracting sha256:75ea8418708338e40dce9179cfe97fd116831f1601be50fef48ea6011653c986                                                                                                                                                     0.9s
 => => extracting sha256:88b459c9f665cc39ff5fc09071b5dada4dad766573d962276f999d0c466d5405                                                                                                                                                     2.3s
 => => extracting sha256:1e3ee139a57774dc3728a4bf9675bc379458093585e42f384852e644b1b272ac                                                                                                                                                     5.6s
 => => extracting sha256:bd2400e7d880dc68db3c01d136b8ee8ed6e846bbc2c97ac0655597a0b11b573a                                                                                                                                                     0.1s
 => => extracting sha256:b8c6812ba46984862fae512c3d1de8299a6819c8159fe022808ec254dc995cc6                                                                                                                                                     0.1s
 => => extracting sha256:0adf07c73141acdb79f289dae7b3a5d8cd2c97c734489092363af2bb7029616a                                                                                                                                                     0.6s
 => => extracting sha256:b24acc262d38a6dd1959ea2863d9c951d977cee55ba0a2f2cb06259a1e1397d1                                                                                                                                                     0.0s
 => [2/2] COPY package.json /usr/src/app/                                                                                                                                                                                                     0.2s
 => ERROR [3/2] RUN npm install                                                                                                                                                                                                               2.9s
------
 > [3/2] RUN npm install:
#7 0.783 npm WARN package.json mockbin@1.6.2 No README data
#7 0.790 npm WARN package.json mockbin@1.6.2 No bin file found at bin/mockbin
#7 1.363 npm WARN deprecated har-validator@5.1.5: this library is no longer supported
#7 1.366 npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
#7 1.387 npm WARN deprecated debug-log@2.0.0: This package is no longer relevant as Node.js 0.12 is unmaintained.
#7 1.438 npm WARN deprecated codeclimate-test-reporter@0.5.1: codeclimate-test-reporter has been deprecated in favor of our new unified test-reporter. Please visit https://docs.codeclimate.com/docs/configuring-test-coverage for details on setting up the new test-reporter.
#7 1.440 npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
#7 1.440 npm WARN deprecated   npm i nyc
#7 1.440 npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
#7 1.709 npm WARN deprecated echint@4.0.2: no longer maintained
#7 2.773 npm ERR! Linux 5.10.25-linuxkit
#7 2.773 npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
#7 2.773 npm ERR! node v0.10.48
#7 2.773 npm ERR! npm  v2.15.1
#7 2.773 npm ERR! code ETARGET
#7 2.774
#7 2.775 npm ERR! notarget No compatible version found: cz-conventional-changelog@'>=3.1.0 <4.0.0'
#7 2.775 npm ERR! notarget Valid install targets:
#7 2.775 npm ERR! notarget ["1.0.0","1.0.1","1.1.0","1.1.1","1.1.2","1.1.3","1.1.4","1.1.5","1.1.6","1.1.7","1.2.0","2.0.0","2.1.0"]
#7 2.775 npm ERR! notarget
#7 2.775 npm ERR! notarget This is most likely not a problem with npm itself.
#7 2.775 npm ERR! notarget In most cases you or one of your dependencies are requesting
#7 2.775 npm ERR! notarget a package version that doesn't exist.
#7 2.775 npm ERR! notarget
#7 2.775 npm ERR! notarget It was specified as a dependency of 'mockbin'
#7 2.775 npm ERR! notarget
#7 2.784
#7 2.784 npm ERR! Please include the following file with any support request:
#7 2.785 npm ERR!     /usr/src/app/npm-debug.log
------
executor failed running [/bin/sh -c npm install]: exit code: 1
```

**Comment by hutchic** [comment]
It manages to build if I bump the node version in the dockerfile. Pushed a branch here feel free to try it out

https://github.com/hutchic/mockbin/tree/chore/bump-node-version

**Comment by jackkav** [comment]
fixed
